version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/pythonwebapp
permissions:
  - object: /var/www/html/pythonwebapp
    pattern: "**"
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
   ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root